# -*- coding: utf-8 -*-
"""YOLOv8_Object_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuvF3S4dD7RcpIVkRl53o5yq99GizxqC
"""

!pip install ultralytics opencv-python matplotlib
import ultralytics
ultralytics.checks()

import os
project_dir = "/content/YOLO_COCO"
os.makedirs(project_dir, exist_ok=True)

print(f"Project directory created at: {project_dir}")

!wget -P /content/YOLO_COCO/ "http://images.cocodataset.org/zips/val2017.zip"
!unzip /content/YOLO_COCO/val2017.zip -d /content/YOLO_COCO/

import os
import cv2
import matplotlib.pyplot as plt

image_folder = "/content/YOLO_COCO/val2017"
image_list = os.listdir(image_folder)

image_path = os.path.join(image_folder, image_list[0])
img = cv2.imread(image_path)
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

plt.imshow(img)
plt.axis("off")
plt.show()

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(data="coco128.yaml", epochs=3, imgsz=640)

image_path = os.path.join(image_folder, image_list[2])
results = model(image_path)

results[0].show()

model.export(format="onnx")

from google.colab import files
files.download("/content/runs/detect/train/weights/best.pt")